spring.application.name=qualifier-1

student.name=Tarun Asharma
student.regNo=0827AL231133
student.email=tarunasharma230709@acropolis.in
api.base.url=https://bfhldevapigw.healthrx.co.in/hiring

server.port=${PORT:8080}

logging.level.com.bajajfinserv.health=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
